version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: apps/gateway/docker/Dockerfile.dev
    container_name: gateway
    ports:
      - "3010:3000"
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=3000
      - HTTP_PORT=3333
      - AUTH_SERVICE_HOST=auth
      - AUTH_SERVICE_PORT=3001
      - EVENT_SERVICE_HOST=event
      - EVENT_SERVICE_PORT=3002
    networks:
      - event-network
    volumes:
      - .:/app
      - ./logs/gateway:/logs/gateway
    depends_on:
      - auth
      - event
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  gateway-fluentd:
    build:
      context: ./config/fluentd
      dockerfile: Dockerfile
    container_name: gateway-fluentd
    volumes:
      - ./logs:/logs
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./logs/system:/fluentd/log/system
      - ./logs/docker:/fluentd/log/docker
      - ./logs/nestjs:/fluentd/log/nestjs
      - ./logs/pos:/fluentd/log/pos
    ports:
      - "24221:24220"
    networks:
      - event-network
    depends_on:
      - gateway
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  auth:
    build:
      context: .
      dockerfile: apps/auth/docker/Dockerfile.dev
    container_name: auth
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo-user:27017
    networks:
      - event-network
    volumes:
      - .:/app
      - ./logs/auth:/logs/auth
    depends_on:
      - mongo-user
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  auth-fluentd:
    build:
      context: ./config/fluentd
      dockerfile: Dockerfile
    container_name: auth-fluentd
    volumes:
      - ./logs:/logs
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./logs/system:/fluentd/log/system
      - ./logs/docker:/fluentd/log/docker
      - ./logs/nestjs:/fluentd/log/nestjs
      - ./logs/pos:/fluentd/log/pos
    ports:
      - "24222:24220"
    networks:
      - event-network
    depends_on:
      - auth
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  event:
    build:
      context: .
      dockerfile: apps/event/docker/Dockerfile.dev
    container_name: event
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo-event:27017
    networks:
      - event-network
    volumes:
      - .:/app
      - ./logs/event:/logs/event
    depends_on:
      - mongo-event
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  event-fluentd:
    build:
      context: ./config/fluentd
      dockerfile: Dockerfile
    container_name: event-fluentd
    volumes:
      - ./logs:/logs
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./logs/system:/fluentd/log/system
      - ./logs/docker:/fluentd/log/docker
      - ./logs/nestjs:/fluentd/log/nestjs
      - ./logs/pos:/fluentd/log/pos
    ports:
      - "24223:24220"
    networks:
      - event-network
    depends_on:
      - event
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  mongo-user:
    image: mongo:latest
    container_name: mongo-user
    ports:
      - "27017:27017"
    volumes:
      - user-data:/data/db
    networks:
      - event-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  mongo-event:
    image: mongo:latest
    container_name: mongo-event
    ports:
      - "27018:27017"
    volumes:
      - event-data:/data/db
    networks:
      - event-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  event-network:
    driver: bridge

volumes:
  user-data:
  event-data:
  logs-volume:
