{
 "title": "Log Viewer",
 "tags": [ "logs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Logs by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({container=~\"$container\"} | pattern `<_>` | pattern `<ts> <level> <msg>` [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Log Count by Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(20, sum by (container)(count_over_time({container=~\"$container\"} [$__interval])))"
    }
   ]
  },
  {
   "title": "Log Count by Path",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(20, sum by (path)(count_over_time({container=~\"$container\", path=~\".+\"} [$__interval])))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=~\"$container\"} |~ \"$search\""
    }
   ]
  }
 ]
}