FROM node:18-alpine

WORKDIR /app

COPY . .

RUN npm install -g pnpm
RUN pnpm install

EXPOSE 3002

# Set the working directory to the event app
WORKDIR /app/apps/event

# Use the shell form of CMD to properly execute the command
CMD ["pnpm", "start:dev"] 
