FROM node:18-alpine

WORKDIR /app

COPY . .

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm build

EXPOSE 3002
EXPOSE 9229

# Set the working directory to the event app
WORKDIR /app/apps/event

# Override with CMD from docker-compose
CMD ["pnpm", "start:prod"] 
