version: '3.9'

services:
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ../infrastructure/loki/local-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    user: "root"
    networks:
      - event-network

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ../infrastructure/alloy/config.river:/etc/alloy/config.river
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../data/alloy:/tmp/alloy
    command: run /etc/alloy/config.river
    user: root
    depends_on:
      - loki
    networks:
      - event-network
    ports:
      - "12345:12345" # For internal metrics
    privileged: true # Add privileged mode for better Docker access

networks:
  event-network:
    external: true 
