version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - event-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    networks:
      - event-network
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ../infrastructure/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../infrastructure/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ../infrastructure/grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - event-network

  # Application services
  gateway:
    build:
      context: ../
      dockerfile: apps/gateway/docker/Dockerfile.dev
    container_name: gateway
    ports:
      - "3010-3015:3000"
      - "3333:3333"
      - "9222:9229"
    environment:
      - NODE_ENV=development
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=3000
      - HTTP_PORT=3333
      - AUTH_SERVICE_HOST=auth
      - AUTH_SERVICE_PORT=3001
      - EVENT_SERVICE_HOST=event
      - EVENT_SERVICE_PORT=3002
    networks:
      - event-network
    volumes:
      - ../:/app
    depends_on:
      - auth
      - event
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "requestId,serviceId"

  auth:
    build:
      context: ../
      dockerfile: apps/auth/docker/Dockerfile.dev
    container_name: auth
    ports:
      - "9223:9229"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo-user:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - event-network
    volumes:
      - ../:/app
    depends_on:
      - mongo-user
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "requestId,serviceId"

  event:
    build:
      context: ../
      dockerfile: apps/event/docker/Dockerfile.dev
    container_name: event
    ports:
      - "9224:9229"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo-event:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - event-network
    volumes:
      - ../:/app
    depends_on:
      - mongo-event
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "requestId,serviceId"

  mongo-user:
    image: mongo:8.0.9
    ports:
      - "27017:27017"
    volumes:
      - user-data:/data/db
    networks:
      - event-network

  mongo-event:
    image: mongo:8.0.9
    ports:
      - "27018:27017"
    volumes:
      - event-data:/data/db
    networks:
      - event-network

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - event-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  event-network:
    driver: bridge
    name: event-network

volumes:
  user-data:
  event-data:
  loki-data:
  grafana-data:
  prometheus-data:
  redis-data:
