FROM node:18-alpine

RUN apk add --no-cache \
    build-base \
    python3 \
    linux-headers 

WORKDIR /app

COPY . .

RUN npm install -g pnpm
RUN pnpm install

EXPOSE 3001

# Set the working directory to the auth app
WORKDIR /app/apps/auth

# Use the shell form of CMD to properly execute the command
CMD ["pnpm", "start:dev"] 
