{
 "title": "Log Viewer",
 "tags": [ "logs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Logs by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({job=\"docker\", service=~\"$service\", service!~\"loki|alloy|grafana\", level=~\".+\"} [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Log Count by Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(service) (count_over_time({job=\"docker\", service!~\"loki|alloy|grafana\"} [1h]))"
    }
   ]
  },
  {
   "title": "Log Count by Path",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(path) (count_over_time({job=\"docker\", service=~\"$service\", service!~\"loki|alloy|grafana\", path=~\".+\"} [24h]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"docker\", service=~\"$service\", service!~\"loki|alloy|grafana\"} |~ \"$search\""
    }
   ]
  }
 ]
}